policy_path: "/home/meetup/g1_deploy/pretrain/loco/policy_29dof.pt"
control_dt: 0.02
kps: [200, 200, 200,
      150, 150, 200,
      150, 150, 200,
      200, 200,      100, 100,
      20,  20,       100, 100,
      20,  20,       50,  50, 
                     50,  50,
                     40,  40,
                     40,  40,
                     40,  40]

kds: [5, 5, 5, 
      5, 5, 5, 
      5, 5, 5, 
      5, 5,     2, 2,
      2, 2,     2, 2, 
      2, 2,     2, 2,
                2, 2,
                2, 2,
                2, 2,
                2, 2]

tau_limit: [88, 88, 88, 139, 50, 50,
            88, 88, 88, 139, 50, 50,
            88, 50, 50,
            25, 25, 25, 25, 5, 5, 5,
            25, 25, 25, 25, 5, 5, 5
           ]

default_angles: [-0.2,  -0.2,  0.0,
                  0.0,   0.0,  0.0,
                  0.0,   0.0,  0.0, 
                  0.42,  0.42,       0.35,  0.35,
                 -0.23, -0.23,       0.18, -0.18, 
                  0.0,   0.0,        0.0,   0.0, 
                                     0.87,  0.87, 
                                     0.0,   0.0, 
                                     0.0,   0.0, 
                                     0.0,   0.0]

action_joint2motor_idx: [0, 6, 12, 
                  1, 7, 13, 
                  2, 8, 14, 
                  3, 9,      15, 22,
                  4, 10,     16, 23, 
                  5, 11,     17, 24, 
                             18, 25, 
                             19, 26, 
                             20, 27, 
                             21, 28]

fixed_target: []

cmd_scale: [1.0, 1.0, 1.0]
cmd_init: [0, 0, 0]
ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 1.0
action_scale: 0.25
num_actions: 29
num_obs: 96
max_cmd: [0.8, 0.5, 1.57]
cmd_range: {lin_vel_x: [-0.4, 0.7], lin_vel_y: [-0.4, 0.4], ang_vel_z: [-1.57, 1.57]}
lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

# === Safty check === 
action_clip: 1.0               # single step clip
action_clip_warn_threshold: 0.8 # warning threshold
debug: true                    # print debug info

dof_pos_lower_limit: [
  -2.5307,
  -0.5236,
  -2.7576,
  -0.087267,
  -0.87267,
  -0.2618,
  -2.5307,
  -2.9671,
  -2.7576,
  -0.087267,
  -0.87267,
  -0.2618,
  -2.618,
  -0.52,
  -0.52,
  -3.0892,
  -1.5882,
  -2.618,
  -1.0472,
  -3.0892,
  -2.2515,
  -2.618,
  -1.0472,
]
dof_pos_upper_limit: [
  2.8798,
  2.9671,
  2.7576,
  2.8798,
  0.5236,
  0.2618,
  2.8798,
  0.5236,
  2.7576,
  2.8798,
  0.5236,
  0.2618,
  2.618,
  0.52,
  0.52,
  2.6704,
  2.2515,
  2.618,
  2.0944,
  2.6704,
  1.5882,
  2.618,
  2.0944,
]
dof_vel_limit: [
  32.0,
  20.0,
  32.0,
  20.0,
  37.0,
  37.0,
  32.0,
  20.0,
  32.0,
  20.0,
  37.0,
  37.0,
  32.0,
  37.0,
  37.0,
  37.0,
  37.0,
  37.0,
  37.0,
  37.0,
  37.0,
  37.0,
  37.0
]
dof_effort_limit: [
  88.0,
  139.0,
  88.0,
  139.0,
  50.0,
  50.0,
  88.0,
  139.0,
  88.0,
  139.0,
  50.0,
  50.0,
  88.0,
  50.0,
  50.0,
  25.0,
  25.0,
  25.0,
  25.0,
  25.0,
  25.0,
  25.0,
  25.0
]